./barn/index.html:15:<a aria-label="Regninga – forsiden" class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./barn/index.html:53:<div class="footer-brand"><a class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./samboer/index.html:18:<a aria-label="Regninga – forsiden" class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./samboer/index.html:87:<div class="footer-brand"><a class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./bolig/index.html:17:<a aria-label="Regninga – forsiden" class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./bolig/index.html:78:<div class="footer-brand"><a class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./404.html:6:<a aria-label="Regninga – forsiden" class="logo" href=""><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./404.html:16:<div class="footer-brand"><a class="logo" href=""><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./index.html:15:<a aria-label="Regninga – forsiden" class="logo" href=""><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./index.html:34:<div class="footer-brand"><a class="logo" href=""><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./personvern.html:17:<a aria-label="Regninga – forsiden" class="logo" href=""><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./personvern.html:49:<div class="footer-brand"><a class="logo" href=""><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./gjeldsfri/index.html:26:<a aria-label="Regninga – forsiden" class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./gjeldsfri/index.html:40:<div class="footer-brand"><a class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./pendling/index.html:15:<a aria-label="Regninga – forsiden" class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./pendling/index.html:56:<div class="footer-brand"><a class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./flytte-hjemmefra/index.html:26:<a aria-label="Regninga – forsiden" class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./flytte-hjemmefra/index.html:40:<div class="footer-brand"><a class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./jobb-mindre/index.html:27:<a aria-label="Regninga – forsiden" class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./jobb-mindre/index.html:180:<div class="footer-brand"><a class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./leie-eller-kjope/index.html:26:<a aria-label="Regninga – forsiden" class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./leie-eller-kjope/index.html:40:<div class="footer-brand"><a class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./banken/index.html:20:<a aria-label="Regninga – forsiden" class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./banken/index.html:67:<div class="footer-brand"><a class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./kontakt.html:4:<a aria-label="Regninga – forsiden" class="logo" href=""><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./kontakt.html:14:<div class="footer-brand"><a class="logo" href=""><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./strom/index.html:18:<a aria-label="Regninga – forsiden" class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./strom/index.html:106:<div class="footer-brand"><a class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./bil/index.html:15:<a aria-label="Regninga – forsiden" class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./bil/index.html:54:<div class="footer-brand"><a class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./pensjon/index.html:24:<a aria-label="Regninga – forsiden" class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./pensjon/index.html:210:<div class="footer-brand"><a class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./pensjon/enkel/index.html:27:<a aria-label="Regninga – forsiden" class="logo" href="../../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./pensjon/enkel/index.html:153:<div class="footer-brand"><a class="logo" href="../../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
./hund/index.html:15:<a aria-label="Regninga – forsiden" class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a>
./hund/index.html:51:<div class="footer-brand"><a class="logo" href="../"><span aria-hidden="true" class="logo-mark"><img alt="" decoding="async" height="40" src="../assets/logo-mark.svg" width="40"/></span><span>Regninga</span></a><p>Enkle kalkulatorer for smartere hverdagsøkonomi.</p></div>
